- name: Install apt repositories
  apt:
    update_cache: yes
    name: "{{ item }}"
  become: true
  with_items:
    - automake
    - build-essential
    - cmake
    - composer
    - curl
    - exuberant-ctags
    - git
    - i3
    - libbz2-dev
    - libffi-dev
    - liblzma-dev
    - libncurses5-dev
    - libncursesw5-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - libtool
    - libtool-bin
    - libxml2-dev
    - libxmlsec1-dev
    - llvm
    - make
    - ppa-purge
    - python-dev
    - python-openssl
    - python-pip
    - python3-pip
    - rake
    - thunar
    - tk-dev
    - tk-dev
    - wget 
    - xz-utils
    - zlib1g-dev
