- name: Install apt repositories
  apt:
    update_cache: yes
    name: "{{ item }}"
  become: true
  with_items:
    - automake
    - build-essential
    - cmake
    - composer
    - curl
    - exuberant-ctags
    - git
    - i3
    - libbz2-dev
    - libffi-dev
    - liblzma-dev
    - libncurses5-dev
    - libncursesw5-dev
    - libreadline-dev
    - libsqlite3-dev
    - libssl-dev
    - libtool
    - libtool-bin
    - libxml2-dev
    - libxmlsec1-dev
    - llvm
    - make
    - ppa-purge
    - python-dev
    - python-openssl
    - python-pip
    - python3-pip
    - rake
    - thunar
    - tk-dev
    - tk-dev
    - wget 
    - xz-utils
    - zlib1g-dev

- name: pyenv | check pyenv installed
  command: test -x {{ home }}/.pyenv/bin/pyenv
  register: pyenv_present
  ignore_errors: yes

- name: pyenv | Clone
  git:
    repo: "https://github.com/pyenv/pyenv.git"
    dest: "{{ pyenv_root }}"
    version: "{{ pyenv_version }}"

- name: pyenv | Clone | pyenv-virtualenv
  git:
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    dest: "{{ pyenv_root }}/plugins/pyenv-virtualenv"
    version: "{{ pyenv_virtualenv_version }}"

- name: pyenv | Clone | virtualenvwrapper
  git:
    repo: https://github.com/pyenv/pyenv-virtualenvwrapper.git
    dest: "{{ pyenv_root }}/plugins/pyenv-virtualenvwrapper"
    version: "{{ pyenv_virtualenvwrapper_version }}"

- name: pyenv | Install | python 2
  shell: " . /home/morais/.bashrc && PYTHON_CONFIGURE_OPTS='--enable-shared' pyenv install 2.7.16"

- name: pyenv | Install | python 3
  shell: " . /home/morais/.bashrc && PYTHON_CONFIGURE_OPTS='--enable-shared' pyenv install 3.7.3"

